github:
  organization: ecmwf
  repositories:
    - fdb
    - eckit
    - metkit
    - fckit
    - dhskit
    - multio
    - eccodes
    - eccodes-python
    - gribjump
    - mars-server
    - mars-client-cpp
    - odc
    - codex

fetch_intervals:
  issues: 30m
  pull_requests: 10m
  actions: 5m

server:
  port: 8000
  host: "0.0.0.0"
