github:
  organization: ecmwf
  repositories:
    - name: fdb
      branches: [master, develop]
    - name: eckit
      branches: [master, develop]
    - name: metkit
      branches: [master, develop]
    - name: fckit
      branches: [master, develop]
    - name: dhskit
      branches: [master, develop]
    - name: multio
      branches: [master, develop]
    - name: eccodes
      branches: [master, develop]
    - name: eccodes-python
      branches: [master, develop]
    - name: gribjump
      branches: [master, develop]
    - name: mars-server
      branches: [master, develop]
    - name: mars-client-cpp
      branches: [master, develop]
    - name: odc
      branches: [master, develop]

fetch_intervals:
  issues: 30m
  pull_requests: 10m
  actions: 5m

server:
  port: 8000
  host: "0.0.0.0"
